<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 ./static/models/home.glb --help
-->

<script>
  import { Group } from 'three'

  import { T } from '@threlte/core'
  import { useGltf, useGltfAnimations } from '@threlte/extras'

  let { fallback, error, children, ref = $bindable(), ...props } = $props()

  ref = new Group()

  const gltf = useGltf('/static/models/home.glb')

  export const { actions, mixer } = useGltfAnimations(gltf, ref)
</script>

<T
  is={ref}
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Group name="Scene">
      <T.Group
        name="SpaceCasset"
        position={[-1.25, 1.92, 0.13]}
        rotation={[Math.PI, -0.61, Math.PI]}
        scale={0.15}
      />
      <T.Group
        name="SpaceMilk"
        position={[1.25, 0.9, -1.55]}
        rotation={[0, 0.84, 0]}
        scale={0.1}
      >
        <T.Group name="SpaceMilk_1">
          <T.Mesh
            name="SpaceMilk_2"
            geometry={gltf.nodes.SpaceMilk_2.geometry}
            material={gltf.materials.spacemilk}
          />
          <T.Mesh
            name="SpaceMilk_3"
            geometry={gltf.nodes.SpaceMilk_3.geometry}
            material={gltf.materials.lightpink}
          />
          <T.Mesh
            name="SpaceMilk_4"
            geometry={gltf.nodes.SpaceMilk_4.geometry}
            material={gltf.materials['Material.004']}
          />
          <T.Mesh
            name="SpaceMilk_5"
            geometry={gltf.nodes.SpaceMilk_5.geometry}
            material={gltf.materials['lightpurple gradient edge']}
          />
          <T.Mesh
            name="SpaceMilk_6"
            geometry={gltf.nodes.SpaceMilk_6.geometry}
            material={gltf.materials['magic gradient']}
          />
          <T.Mesh
            name="SpaceMilk_7"
            geometry={gltf.nodes.SpaceMilk_7.geometry}
            material={gltf.materials['translucent top']}
          />
          <T.Mesh
            name="SpaceMilk_8"
            geometry={gltf.nodes.SpaceMilk_8.geometry}
            material={gltf.materials['purple gradient']}
          />
          <T.Mesh
            name="SpaceMilk_9"
            geometry={gltf.nodes.SpaceMilk_9.geometry}
            material={gltf.materials['Material.002']}
          />
        </T.Group>
      </T.Group>
      <T.Group
        name="SpacePotion"
        position={[0.08, 0.24, -0.07]}
        rotation={[-1.71, 0.14, -0.78]}
        scale={0.1}
      >
        <T.Group name="SpacePotion_1">
          <T.Mesh
            name="SpacePotion_2"
            geometry={gltf.nodes.SpacePotion_2.geometry}
            material={gltf.materials['liquid outline cork']}
          />
          <T.Mesh
            name="SpacePotion_3"
            geometry={gltf.nodes.SpacePotion_3.geometry}
            material={gltf.materials.rendered}
          />
          <T.Mesh
            name="SpacePotion_4"
            geometry={gltf.nodes.SpacePotion_4.geometry}
            material={gltf.materials.reflection}
          />
          <T.Mesh
            name="SpacePotion_5"
            geometry={gltf.nodes.SpacePotion_5.geometry}
            material={gltf.materials['liquid outline']}
          />
          <T.Mesh
            name="SpacePotion_6"
            geometry={gltf.nodes.SpacePotion_6.geometry}
            material={gltf.materials['liquid outline lighter']}
          />
          <T.Mesh
            name="SpacePotion_7"
            geometry={gltf.nodes.SpacePotion_7.geometry}
            material={gltf.materials.glass}
          />
          <T.Mesh
            name="SpacePotion_8"
            geometry={gltf.nodes.SpacePotion_8.geometry}
            material={gltf.materials.cork}
          />
          <T.Mesh
            name="SpacePotion_9"
            geometry={gltf.nodes.SpacePotion_9.geometry}
            material={gltf.materials['space liquid']}
          />
        </T.Group>
      </T.Group>
      <T.Group
        name="SpaceSpeaker"
        position={[-1.15, 1.15, -0.73]}
        rotation={[0, Math.PI / 3, 0]}
        scale={0.15}
      >
        <T.Group name="SpaceSpeaker_1">
          <T.Mesh
            name="SpaceSpeaker_2"
            geometry={gltf.nodes.SpaceSpeaker_2.geometry}
            material={gltf.materials.outline}
          />
          <T.Mesh
            name="SpaceSpeaker_3"
            geometry={gltf.nodes.SpaceSpeaker_3.geometry}
            material={gltf.materials.liquid}
          />
          <T.Mesh
            name="SpaceSpeaker_4"
            geometry={gltf.nodes.SpaceSpeaker_4.geometry}
            material={gltf.materials.top}
          />
          <T.Mesh
            name="SpaceSpeaker_5"
            geometry={gltf.nodes.SpaceSpeaker_5.geometry}
            material={gltf.materials['highlights side']}
          />
          <T.Mesh
            name="SpaceSpeaker_6"
            geometry={gltf.nodes.SpaceSpeaker_6.geometry}
            material={gltf.materials['highlights top']}
          />
          <T.Mesh
            name="SpaceSpeaker_7"
            geometry={gltf.nodes.SpaceSpeaker_7.geometry}
            material={gltf.materials.magic}
          />
          <T.Mesh
            name="SpaceSpeaker_8"
            geometry={gltf.nodes.SpaceSpeaker_8.geometry}
            material={gltf.materials.bass}
          />
          <T.Mesh
            name="SpaceSpeaker_9"
            geometry={gltf.nodes.SpaceSpeaker_9.geometry}
            material={gltf.materials.treble}
          />
          <T.Mesh
            name="SpaceSpeaker_10"
            geometry={gltf.nodes.SpaceSpeaker_10.geometry}
            material={gltf.materials['liquid.001']}
          />
          <T.Mesh
            name="SpaceSpeaker_11"
            geometry={gltf.nodes.SpaceSpeaker_11.geometry}
            material={gltf.materials.bottom}
          />
        </T.Group>
      </T.Group>
      <T.Group
        name="PC"
        position={[-1.1, 0.88, -1.85]}
      >
        <T.Group name="PC_1">
          <T.Mesh
            name="PC_2"
            geometry={gltf.nodes.PC_2.geometry}
            material={gltf.materials.Computer}
          />
          <T.Mesh
            name="PC_3"
            geometry={gltf.nodes.PC_3.geometry}
            material={gltf.materials.Glass}
          />
          <T.Mesh
            name="PC_4"
            geometry={gltf.nodes.PC_4.geometry}
            material={gltf.materials.Exhaust}
          />
          <T.Mesh
            name="PC_5"
            geometry={gltf.nodes.PC_5.geometry}
            material={gltf.materials.BasePurple}
          />
          <T.Mesh
            name="Rotor_1"
            geometry={gltf.nodes.Rotor_1.geometry}
            material={gltf.materials.BaseWhite}
            position={[0.11, 0.24, -0.09]}
          />
          <T.Mesh
            name="Rotor_2"
            geometry={gltf.nodes.Rotor_2.geometry}
            material={gltf.materials.BaseWhite}
            position={[-0.03, 0.28, -0.33]}
          />
          <T.Mesh
            name="Rotor_3"
            geometry={gltf.nodes.Rotor_3.geometry}
            material={gltf.materials.BaseWhite}
            position={[0.11, 0.24, 0.04]}
          />
          <T.Mesh
            name="Rotor_4"
            geometry={gltf.nodes.Rotor_4.geometry}
            material={gltf.materials.BaseWhite}
            position={[-0.03, 0.41, -0.33]}
          />
          <T.Mesh
            name="Rotor_5"
            geometry={gltf.nodes.Rotor_5.geometry}
            material={gltf.materials.BaseWhite}
            position={[0.11, 0.24, 0.18]}
          />
        </T.Group>
      </T.Group>
      <T.Group
        name="Fich"
        position={[1, 0.4, 0.25]}
      >
        <T.Mesh
          name="Bowl"
          geometry={gltf.nodes.Bowl.geometry}
          material={gltf.materials.Glass}
        >
          <T.Mesh
            name="Fish"
            geometry={gltf.nodes.Fish.geometry}
            material={gltf.materials.Goldfish}
            rotation={[0, 0.03, 0]}
          >
            <T.Mesh
              name="Eye_1"
              geometry={gltf.nodes.Eye_1.geometry}
              material={gltf.materials.Eyeball}
            />
            <T.Mesh
              name="Eye_2"
              geometry={gltf.nodes.Eye_2.geometry}
              material={gltf.materials.Eyeball}
            />
          </T.Mesh>
          <T.Mesh
            name="Water"
            geometry={gltf.nodes.Water.geometry}
            material={gltf.materials.WaterHigherTransparency}
          />
        </T.Mesh>
      </T.Group>
      <T.Group
        name="Cair"
        position={[-0.3, 0.13, -0.8]}
        rotation={[0, -Math.PI / 6, 0]}
      >
        <T.Group name="Chair">
          <T.Mesh
            name="ChairTop"
            geometry={gltf.nodes.ChairTop.geometry}
            material={gltf.materials.ChairCushion}
          />
          <T.Mesh
            name="ChairTop_1"
            geometry={gltf.nodes.ChairTop_1.geometry}
            material={gltf.materials.ChairGray}
          />
        </T.Group>
        <T.Group name="ChairLegs">
          <T.Mesh
            name="ChairLegs_1"
            geometry={gltf.nodes.ChairLegs_1.geometry}
            material={gltf.materials.ChairGray}
          />
          <T.Mesh
            name="ChairLegs_2"
            geometry={gltf.nodes.ChairLegs_2.geometry}
            material={gltf.materials.BaseBlack}
          />
        </T.Group>
      </T.Group>
      <T.Group
        name="SpaceJuice"
        position={[0.25, 0.6, 0.8]}
        rotation={[-0.2, -0.51, -0.1]}
        scale={0.05}
      >
        <T.Group name="SpaceJuice_1">
          <T.Mesh
            name="SpaceJuice_2"
            geometry={gltf.nodes.SpaceJuice_2.geometry}
            material={gltf.materials.liquid}
          />
          <T.Mesh
            name="SpaceJuice_3"
            geometry={gltf.nodes.SpaceJuice_3.geometry}
            material={gltf.materials.liquidtop}
          />
          <T.Mesh
            name="SpaceJuice_4"
            geometry={gltf.nodes.SpaceJuice_4.geometry}
            material={gltf.materials['Outline.001']}
          />
          <T.Mesh
            name="SpaceJuice_5"
            geometry={gltf.nodes.SpaceJuice_5.geometry}
            material={gltf.materials.box_base}
          />
          <T.Mesh
            name="SpaceJuice_6"
            geometry={gltf.nodes.SpaceJuice_6.geometry}
            material={gltf.materials.IMG_1142}
          />
          <T.Mesh
            name="SpaceJuice_7"
            geometry={gltf.nodes.SpaceJuice_7.geometry}
            material={gltf.materials.Material}
          />
          <T.Mesh
            name="SpaceJuice_8"
            geometry={gltf.nodes.SpaceJuice_8.geometry}
            material={gltf.materials['light green layerweight']}
          />
          <T.Mesh
            name="SpaceJuice_9"
            geometry={gltf.nodes.SpaceJuice_9.geometry}
            material={gltf.materials['Outline.003']}
          />
          <T.Mesh
            name="SpaceJuice_10"
            geometry={gltf.nodes.SpaceJuice_10.geometry}
            material={gltf.materials.dots}
          />
          <T.Mesh
            name="SpaceJuice_11"
            geometry={gltf.nodes.SpaceJuice_11.geometry}
            material={gltf.materials['dark purple line']}
          />
          <T.Mesh
            name="SpaceJuice_12"
            geometry={gltf.nodes.SpaceJuice_12.geometry}
            material={gltf.materials.recyclabe}
          />
        </T.Group>
      </T.Group>
      <T.Group
        name="SpaceCasset001"
        position={[-1.25, 1.92, 0.13]}
        rotation={[Math.PI, -0.61, Math.PI]}
        scale={0.15}
      >
        <T.Group name="SpaceCasset_1">
          <T.Mesh
            name="Plane"
            geometry={gltf.nodes.Plane.geometry}
            material={gltf.materials.Render}
          />
          <T.Mesh
            name="Plane_1"
            geometry={gltf.nodes.Plane_1.geometry}
            material={gltf.materials.transparent}
          />
          <T.Mesh
            name="Plane_2"
            geometry={gltf.nodes.Plane_2.geometry}
            material={gltf.materials.metal_refl}
          />
          <T.Mesh
            name="Plane_3"
            geometry={gltf.nodes.Plane_3.geometry}
            material={gltf.materials['dark purple']}
          />
          <T.Mesh
            name="Plane_4"
            geometry={gltf.nodes.Plane_4.geometry}
            material={gltf.materials.outline}
          />
          <T.Mesh
            name="Plane_5"
            geometry={gltf.nodes.Plane_5.geometry}
            material={gltf.materials.Material}
          />
          <T.Mesh
            name="Plane_6"
            geometry={gltf.nodes.Plane_6.geometry}
            material={gltf.materials.circle}
          />
          <T.Mesh
            name="Plane_7"
            geometry={gltf.nodes.Plane_7.geometry}
            material={gltf.materials.text}
          />
        </T.Group>
      </T.Group>
      <T.Group name="Plane001">
        <T.Mesh
          name="Plane001_1"
          geometry={gltf.nodes.Plane001_1.geometry}
          material={gltf.materials.LeatherCracked}
        />
        <T.Mesh
          name="Plane001_2"
          geometry={gltf.nodes.Plane001_2.geometry}
          material={gltf.materials.WoodDark}
        />
        <T.Mesh
          name="Plane001_3"
          geometry={gltf.nodes.Plane001_3.geometry}
          material={gltf.materials.WoodLast}
        />
        <T.Mesh
          name="Plane001_4"
          geometry={gltf.nodes.Plane001_4.geometry}
          material={gltf.materials.BaseWhite}
        />
        <T.Mesh
          name="Plane001_5"
          geometry={gltf.nodes.Plane001_5.geometry}
          material={gltf.materials.Gold}
        />
        <T.Mesh
          name="Plane001_6"
          geometry={gltf.nodes.Plane001_6.geometry}
          material={gltf.materials.Cartton}
        />
        <T.Mesh
          name="Plane001_7"
          geometry={gltf.nodes.Plane001_7.geometry}
          material={gltf.materials.CarttonHandle}
        />
        <T.Mesh
          name="Plane001_8"
          geometry={gltf.nodes.Plane001_8.geometry}
          material={gltf.materials.CarttonCap}
        />
        <T.Mesh
          name="Plane001_9"
          geometry={gltf.nodes.Plane001_9.geometry}
          material={gltf.materials.Emission}
        />
        <T.Mesh
          name="Plane001_10"
          geometry={gltf.nodes.Plane001_10.geometry}
          material={gltf.materials.PlasticBasicBlack}
        />
        <T.Mesh
          name="Plane001_11"
          geometry={gltf.nodes.Plane001_11.geometry}
          material={gltf.materials.Cover}
        />
        <T.Mesh
          name="Plane001_12"
          geometry={gltf.nodes.Plane001_12.geometry}
          material={gltf.materials.Paper}
        />
        <T.Mesh
          name="Plane001_13"
          geometry={gltf.nodes.Plane001_13.geometry}
          material={gltf.materials.Keyboard}
        />
        <T.Mesh
          name="Plane001_14"
          geometry={gltf.nodes.Plane001_14.geometry}
          material={gltf.materials.BasePurple}
        />
        <T.Mesh
          name="Plane001_15"
          geometry={gltf.nodes.Plane001_15.geometry}
          material={gltf.materials.BaseBlueTwo}
        />
        <T.Mesh
          name="Plane001_16"
          geometry={gltf.nodes.Plane001_16.geometry}
          material={gltf.materials.BaseBrown}
        />
        <T.Mesh
          name="Plane001_17"
          geometry={gltf.nodes.Plane001_17.geometry}
          material={gltf.materials.Picture}
        />
        <T.Mesh
          name="Plane001_18"
          geometry={gltf.nodes.Plane001_18.geometry}
          material={gltf.materials.WoodLight}
        />
        <T.Mesh
          name="Plane001_19"
          geometry={gltf.nodes.Plane001_19.geometry}
          material={gltf.materials.LampShade}
        />
        <T.Mesh
          name="Plane001_20"
          geometry={gltf.nodes.Plane001_20.geometry}
          material={gltf.materials.LampBase}
        />
        <T.Mesh
          name="Plane001_21"
          geometry={gltf.nodes.Plane001_21.geometry}
          material={gltf.materials.LavendelStem}
        />
        <T.Mesh
          name="Plane001_22"
          geometry={gltf.nodes.Plane001_22.geometry}
          material={gltf.materials['Modern Fiberstone']}
        />
        <T.Mesh
          name="Plane001_23"
          geometry={gltf.nodes.Plane001_23.geometry}
          material={gltf.materials.GardenSoil}
        />
        <T.Mesh
          name="Plane001_24"
          geometry={gltf.nodes.Plane001_24.geometry}
          material={gltf.materials.BaseGrey}
        />
        <T.Mesh
          name="Plane001_25"
          geometry={gltf.nodes.Plane001_25.geometry}
          material={gltf.materials.TextMaterial}
        />
        <T.Mesh
          name="Plane001_26"
          geometry={gltf.nodes.Plane001_26.geometry}
          material={gltf.materials.GithubLogo}
        />
        <T.Mesh
          name="Plane001_27"
          geometry={gltf.nodes.Plane001_27.geometry}
          material={gltf.materials['Light Wooden']}
        />
        <T.Mesh
          name="Plane001_28"
          geometry={gltf.nodes.Plane001_28.geometry}
          material={gltf.materials.YouTubeLogo}
        />
        <T.Mesh
          name="Plane001_29"
          geometry={gltf.nodes.Plane001_29.geometry}
          material={gltf.materials.TwitterLogo}
        />
        <T.Mesh
          name="Plane001_30"
          geometry={gltf.nodes.Plane001_30.geometry}
          material={gltf.materials.InstagramLogo}
        />
        <T.Mesh
          name="Plane001_31"
          geometry={gltf.nodes.Plane001_31.geometry}
          material={gltf.materials.Glass}
        />
        <T.Mesh
          name="Plane001_32"
          geometry={gltf.nodes.Plane001_32.geometry}
          material={gltf.materials.P1SColor}
        />
        <T.Mesh
          name="Plane001_33"
          geometry={gltf.nodes.Plane001_33.geometry}
          material={gltf.materials.LavendelHead}
        />
        <T.Mesh
          name="Plane001_34"
          geometry={gltf.nodes.Plane001_34.geometry}
          material={gltf.materials.LavendelPetal}
        />
        <T.Mesh
          name="Plane001_35"
          geometry={gltf.nodes.Plane001_35.geometry}
          material={gltf.materials.FabricWeaved}
        />
        <T.Mesh
          name="Plane001_36"
          geometry={gltf.nodes.Plane001_36.geometry}
          material={gltf.materials.LightBase}
        />
        <T.Mesh
          name="Plane001_37"
          geometry={gltf.nodes.Plane001_37.geometry}
          material={gltf.materials.BaseBlack}
        />
        <T.Mesh
          name="Plane001_38"
          geometry={gltf.nodes.Plane001_38.geometry}
          material={gltf.materials.FabricWeavedDark}
        />
        <T.Mesh
          name="Plane001_39"
          geometry={gltf.nodes.Plane001_39.geometry}
          material={gltf.materials.Cactus}
        />
        <T.Mesh
          name="Plane001_40"
          geometry={gltf.nodes.Plane001_40.geometry}
          material={gltf.materials.RubberBumpy}
        />
        <T.Mesh
          name="Plane001_41"
          geometry={gltf.nodes.Plane001_41.geometry}
          material={gltf.materials['Material.011']}
        />
        <T.Mesh
          name="Plane001_42"
          geometry={gltf.nodes.Plane001_42.geometry}
          material={gltf.materials['Material.012']}
        />
        <T.Mesh
          name="Plane001_43"
          geometry={gltf.nodes.Plane001_43.geometry}
          material={gltf.materials['Material.014']}
        />
        <T.Mesh
          name="Plane001_44"
          geometry={gltf.nodes.Plane001_44.geometry}
          material={gltf.materials['Material.015']}
        />
        <T.Mesh
          name="Plane001_45"
          geometry={gltf.nodes.Plane001_45.geometry}
          material={gltf.materials['Material.017']}
        />
        <T.Mesh
          name="Plane001_46"
          geometry={gltf.nodes.Plane001_46.geometry}
          material={gltf.materials['Material.018']}
        />
        <T.Mesh
          name="Plane001_47"
          geometry={gltf.nodes.Plane001_47.geometry}
          material={gltf.materials['Material.019']}
        />
        <T.Mesh
          name="Plane001_48"
          geometry={gltf.nodes.Plane001_48.geometry}
          material={gltf.materials.Kirby}
        />
      </T.Group>
    </T.Group>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T>
