<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0-next.11 /home/default/node/me/static/models/home.glb --root /models/ --keepnames --meta --shadows --printwidth 120 --precision 2 --draco ./ --preload --suspense --isolated --transform --resolution 1024 --simplify --weld 0.0001 --ratio 0.75 --error 0.001
-->

<script module>
  import { Group } from 'three'

  import { T } from '@threlte/core'
  import { useGltf, useGltfAnimations, useSuspense, useDraco } from '@threlte/extras'

  const load = () => {
    const suspend = useSuspense()
    return suspend(useGltf('/models/home-transformed.glb', { dracoLoader: useDraco() }))
  }

  export const preload = async () => {
    await load()
  }
</script>

<script>
  let { fallback, error, children } = $props()

  const ref = new Group()

  const gltf = load()

  export const { actions, mixer } = useGltfAnimations(gltf, ref)
</script>

<T
  is={ref}
  dispose={false}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Group name="Scene">
      <T.Group
        name="SpaceMilk"
        position={[1.1, 0.9, -1.65]}
        rotation={[0, 0.84, 0]}
        scale={0.1}
        userData={{ name: 'SpaceMilk' }}
      >
        <T.Group
          name="SpaceMilk_1"
          userData={{ name: 'SpaceMilk' }}
        >
          <T.Mesh
            name="SpaceMilk_2"
            castShadow
            receiveShadow
            geometry={gltf.nodes.SpaceMilk_2.geometry}
            material={gltf.materials.spacemilk}
          />
          <T.Mesh
            name="SpaceMilk_3"
            castShadow
            receiveShadow
            geometry={gltf.nodes.SpaceMilk_3.geometry}
            material={gltf.materials.lightpink}
          />
          <T.Mesh
            name="SpaceMilk_4"
            castShadow
            receiveShadow
            geometry={gltf.nodes.SpaceMilk_4.geometry}
            material={gltf.materials['Material.004']}
          />
          <T.Mesh
            name="SpaceMilk_5"
            castShadow
            receiveShadow
            geometry={gltf.nodes.SpaceMilk_5.geometry}
            material={gltf.materials['lightpurple gradient edge']}
          />
          <T.Mesh
            name="SpaceMilk_6"
            castShadow
            receiveShadow
            geometry={gltf.nodes.SpaceMilk_6.geometry}
            material={gltf.materials['magic gradient']}
          />
          <T.Mesh
            name="SpaceMilk_7"
            castShadow
            receiveShadow
            geometry={gltf.nodes.SpaceMilk_7.geometry}
            material={gltf.materials['translucent top']}
          />
          <T.Mesh
            name="SpaceMilk_8"
            castShadow
            receiveShadow
            geometry={gltf.nodes.SpaceMilk_8.geometry}
            material={gltf.materials['purple gradient']}
          />
          <T.Mesh
            name="SpaceMilk_9"
            castShadow
            receiveShadow
            geometry={gltf.nodes.SpaceMilk_9.geometry}
            material={gltf.materials['Material.002']}
          />
        </T.Group>
      </T.Group>
      <T.Group
        name="SpacePotion"
        position={[0.08, 0.24, -0.07]}
        rotation={[-1.71, 0.14, -0.78]}
        scale={0.1}
        userData={{ name: 'SpacePotion' }}
      >
        <T.Group
          name="SpacePotion_1"
          userData={{ name: 'SpacePotion' }}
        >
          <T.Mesh
            name="SpacePotion_2"
            castShadow
            receiveShadow
            geometry={gltf.nodes.SpacePotion_2.geometry}
            material={gltf.materials['liquid outline cork']}
          />
          <T.Mesh
            name="SpacePotion_3"
            castShadow
            receiveShadow
            geometry={gltf.nodes.SpacePotion_3.geometry}
            material={gltf.materials.rendered}
          />
          <T.Mesh
            name="SpacePotion_4"
            castShadow
            receiveShadow
            geometry={gltf.nodes.SpacePotion_4.geometry}
            material={gltf.materials.reflection}
          />
          <T.Mesh
            name="SpacePotion_5"
            castShadow
            receiveShadow
            geometry={gltf.nodes.SpacePotion_5.geometry}
            material={gltf.materials['liquid outline']}
          />
          <T.Mesh
            name="SpacePotion_6"
            castShadow
            receiveShadow
            geometry={gltf.nodes.SpacePotion_6.geometry}
            material={gltf.materials['liquid outline']}
          />
          <T.Mesh
            name="SpacePotion_7"
            castShadow
            receiveShadow
            geometry={gltf.nodes.SpacePotion_7.geometry}
            material={gltf.materials.glass}
          />
          <T.Mesh
            name="SpacePotion_8"
            castShadow
            receiveShadow
            geometry={gltf.nodes.SpacePotion_8.geometry}
            material={gltf.materials.cork}
          />
          <T.Mesh
            name="SpacePotion_9"
            castShadow
            receiveShadow
            geometry={gltf.nodes.SpacePotion_9.geometry}
            material={gltf.materials['space liquid']}
          />
        </T.Group>
      </T.Group>
      <T.Group
        name="SpaceSpeaker"
        position={[-1.15, 1.15, -0.74]}
        rotation={[0, Math.PI / 3, 0]}
        scale={0.15}
        userData={{ name: 'SpaceSpeaker' }}
      >
        <T.Group
          name="SpaceSpeaker_1"
          userData={{ name: 'SpaceSpeaker' }}
        >
          <T.Mesh
            name="SpaceSpeaker_2"
            castShadow
            receiveShadow
            geometry={gltf.nodes.SpaceSpeaker_2.geometry}
            material={gltf.materials.outline}
          />
          <T.Mesh
            name="SpaceSpeaker_3"
            castShadow
            receiveShadow
            geometry={gltf.nodes.SpaceSpeaker_3.geometry}
            material={gltf.materials.liquid}
          />
          <T.Mesh
            name="SpaceSpeaker_4"
            castShadow
            receiveShadow
            geometry={gltf.nodes.SpaceSpeaker_4.geometry}
            material={gltf.materials.top}
          />
          <T.Mesh
            name="SpaceSpeaker_5"
            castShadow
            receiveShadow
            geometry={gltf.nodes.SpaceSpeaker_5.geometry}
            material={gltf.materials['highlights side']}
          />
          <T.Mesh
            name="SpaceSpeaker_6"
            castShadow
            receiveShadow
            geometry={gltf.nodes.SpaceSpeaker_6.geometry}
            material={gltf.materials['highlights top']}
          />
          <T.Mesh
            name="SpaceSpeaker_7"
            castShadow
            receiveShadow
            geometry={gltf.nodes.SpaceSpeaker_7.geometry}
            material={gltf.materials.magic}
          />
          <T.Mesh
            name="SpaceSpeaker_8"
            castShadow
            receiveShadow
            geometry={gltf.nodes.SpaceSpeaker_8.geometry}
            material={gltf.materials.bass}
          />
          <T.Mesh
            name="SpaceSpeaker_9"
            castShadow
            receiveShadow
            geometry={gltf.nodes.SpaceSpeaker_9.geometry}
            material={gltf.materials.bass}
          />
          <T.Mesh
            name="SpaceSpeaker_10"
            castShadow
            receiveShadow
            geometry={gltf.nodes.SpaceSpeaker_10.geometry}
            material={gltf.materials['liquid.001']}
          />
          <T.Mesh
            name="SpaceSpeaker_11"
            castShadow
            receiveShadow
            geometry={gltf.nodes.SpaceSpeaker_11.geometry}
            material={gltf.materials.bottom}
          />
        </T.Group>
      </T.Group>
      <T.Group
        name="PC"
        position={[-1.11, 0.88, -1.85]}
        userData={{ name: 'PC' }}
      >
        <T.Group
          name="PC_1"
          userData={{ name: 'PC' }}
        >
          <T.Mesh
            name="PC_2"
            castShadow
            receiveShadow
            geometry={gltf.nodes.PC_2.geometry}
            material={gltf.materials.Computer}
          />
          <T.Mesh
            name="PC_3"
            castShadow
            receiveShadow
            geometry={gltf.nodes.PC_3.geometry}
            material={gltf.materials.Glass}
          />
          <T.Mesh
            name="PC_4"
            castShadow
            receiveShadow
            geometry={gltf.nodes.PC_4.geometry}
            material={gltf.materials.Exhaust}
          />
          <T.Mesh
            name="PC_5"
            castShadow
            receiveShadow
            geometry={gltf.nodes.PC_5.geometry}
            material={gltf.materials.BasePurple}
          />
          <T.Mesh
            name="Rotor_1"
            castShadow
            receiveShadow
            geometry={gltf.nodes.Rotor_1.geometry}
            material={gltf.materials.BaseWhite}
            position={[0.11, 0.24, -0.09]}
            userData={{ name: 'Rotor_1' }}
          />
          <T.Mesh
            name="Rotor_2"
            castShadow
            receiveShadow
            geometry={gltf.nodes.Rotor_2.geometry}
            material={gltf.materials.BaseWhite}
            position={[-0.03, 0.28, -0.33]}
            userData={{ name: 'Rotor_2' }}
          />
          <T.Mesh
            name="Rotor_3"
            castShadow
            receiveShadow
            geometry={gltf.nodes.Rotor_3.geometry}
            material={gltf.materials.BaseWhite}
            position={[0.11, 0.24, 0.04]}
            userData={{ name: 'Rotor_3' }}
          />
          <T.Mesh
            name="Rotor_4"
            castShadow
            receiveShadow
            geometry={gltf.nodes.Rotor_4.geometry}
            material={gltf.materials.BaseWhite}
            position={[-0.03, 0.41, -0.33]}
            userData={{ name: 'Rotor_4' }}
          />
          <T.Mesh
            name="Rotor_5"
            castShadow
            receiveShadow
            geometry={gltf.nodes.Rotor_5.geometry}
            material={gltf.materials.BaseWhite}
            position={[0.11, 0.24, 0.18]}
            userData={{ name: 'Rotor_5' }}
          />
        </T.Group>
      </T.Group>
      <T.Group
        name="Fich"
        position={[1, 0.4, 0.25]}
        userData={{ name: 'Fich' }}
      >
        <T.Mesh
          name="Bowl"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Bowl.geometry}
          material={gltf.materials.Glass}
          userData={{ name: 'Bowl' }}
        >
          <T.Mesh
            name="Fish"
            castShadow
            receiveShadow
            geometry={gltf.nodes.Fish.geometry}
            material={gltf.materials.Goldfish}
            rotation={[0, 0.03, 0]}
            userData={{ name: 'Fish' }}
          >
            <T.Mesh
              name="Eye_1"
              castShadow
              receiveShadow
              geometry={gltf.nodes.Eye_1.geometry}
              material={gltf.materials.Eyeball}
              userData={{ name: 'Eye_1' }}
            />
            <T.Mesh
              name="Eye_2"
              castShadow
              receiveShadow
              geometry={gltf.nodes.Eye_2.geometry}
              material={gltf.materials.Eyeball}
              userData={{ name: 'Eye_2' }}
            />
          </T.Mesh>
          <T.Mesh
            name="Water"
            castShadow
            receiveShadow
            geometry={gltf.nodes.Water.geometry}
            material={gltf.materials.WaterHigherTransparency}
            userData={{ name: 'Water' }}
          />
        </T.Mesh>
      </T.Group>
      <T.Group
        name="Cair"
        position={[-0.3, 0.13, -0.8]}
        rotation={[0, -Math.PI / 6, 0]}
        userData={{ name: 'Cair' }}
      >
        <T.Group
          name="Chair"
          userData={{ name: 'Chair' }}
        >
          <T.Mesh
            name="ChairTop"
            castShadow
            receiveShadow
            geometry={gltf.nodes.ChairTop.geometry}
            material={gltf.materials.ChairCushion}
          />
          <T.Mesh
            name="ChairTop_1"
            castShadow
            receiveShadow
            geometry={gltf.nodes.ChairTop_1.geometry}
            material={gltf.materials.ChairGray}
          />
        </T.Group>
        <T.Group
          name="ChairLegs"
          userData={{ name: 'ChairLegs' }}
        >
          <T.Mesh
            name="ChairLegs_1"
            castShadow
            receiveShadow
            geometry={gltf.nodes.ChairLegs_1.geometry}
            material={gltf.materials.ChairGray}
          />
          <T.Mesh
            name="ChairLegs_2"
            castShadow
            receiveShadow
            geometry={gltf.nodes.ChairLegs_2.geometry}
            material={gltf.materials.BaseBlack}
          />
        </T.Group>
      </T.Group>
      <T.Group
        name="SpaceJuice"
        position={[0.35, 0.6, 0.9]}
        rotation={[-0.2, -0.51, -0.1]}
        scale={0.05}
        userData={{ name: 'SpaceJuice' }}
      >
        <T.Group
          name="SpaceJuice_1"
          userData={{ name: 'SpaceJuice' }}
        >
          <T.Mesh
            name="SpaceJuice_2"
            castShadow
            receiveShadow
            geometry={gltf.nodes.SpaceJuice_2.geometry}
            material={gltf.materials.liquid}
          />
          <T.Mesh
            name="SpaceJuice_3"
            castShadow
            receiveShadow
            geometry={gltf.nodes.SpaceJuice_3.geometry}
            material={gltf.materials.liquidtop}
          />
          <T.Mesh
            name="SpaceJuice_4"
            castShadow
            receiveShadow
            geometry={gltf.nodes.SpaceJuice_4.geometry}
            material={gltf.materials['Outline.001']}
          />
          <T.Mesh
            name="SpaceJuice_5"
            castShadow
            receiveShadow
            geometry={gltf.nodes.SpaceJuice_5.geometry}
            material={gltf.materials.box_base}
          />
          <T.Mesh
            name="SpaceJuice_6"
            castShadow
            receiveShadow
            geometry={gltf.nodes.SpaceJuice_6.geometry}
            material={gltf.materials.IMG_1142}
          />
          <T.Mesh
            name="SpaceJuice_7"
            castShadow
            receiveShadow
            geometry={gltf.nodes.SpaceJuice_7.geometry}
            material={gltf.materials.Material}
          />
          <T.Mesh
            name="SpaceJuice_8"
            castShadow
            receiveShadow
            geometry={gltf.nodes.SpaceJuice_8.geometry}
            material={gltf.materials['light green layerweight']}
          />
          <T.Mesh
            name="SpaceJuice_9"
            castShadow
            receiveShadow
            geometry={gltf.nodes.SpaceJuice_9.geometry}
            material={gltf.materials['Outline.003']}
          />
          <T.Mesh
            name="SpaceJuice_10"
            castShadow
            receiveShadow
            geometry={gltf.nodes.SpaceJuice_10.geometry}
            material={gltf.materials.dots}
          />
          <T.Mesh
            name="SpaceJuice_11"
            castShadow
            receiveShadow
            geometry={gltf.nodes.SpaceJuice_11.geometry}
            material={gltf.materials['dark purple line']}
          />
          <T.Mesh
            name="SpaceJuice_12"
            castShadow
            receiveShadow
            geometry={gltf.nodes.SpaceJuice_12.geometry}
            material={gltf.materials.recyclabe}
          />
        </T.Group>
      </T.Group>
      <T.Group
        name="SpaceCasset"
        position={[-1.25, 1.92, 0.13]}
        rotation={[Math.PI, -0.61, Math.PI]}
        scale={0.15}
        userData={{ name: 'SpaceCasset' }}
      >
        <T.Group
          name="SpaceCasset_1"
          userData={{ name: 'SpaceCasset' }}
        >
          <T.Mesh
            name="SpaceCasset_2"
            castShadow
            receiveShadow
            geometry={gltf.nodes.SpaceCasset_2.geometry}
            material={gltf.materials.Render}
          />
          <T.Mesh
            name="SpaceCasset_3"
            castShadow
            receiveShadow
            geometry={gltf.nodes.SpaceCasset_3.geometry}
            material={gltf.materials.transparent}
          />
          <T.Mesh
            name="SpaceCasset_4"
            castShadow
            receiveShadow
            geometry={gltf.nodes.SpaceCasset_4.geometry}
            material={gltf.materials.metal_refl}
          />
          <T.Mesh
            name="SpaceCasset_5"
            castShadow
            receiveShadow
            geometry={gltf.nodes.SpaceCasset_5.geometry}
            material={gltf.materials['dark purple']}
          />
          <T.Mesh
            name="SpaceCasset_6"
            castShadow
            receiveShadow
            geometry={gltf.nodes.SpaceCasset_6.geometry}
            material={gltf.materials.outline}
          />
          <T.Mesh
            name="SpaceCasset_7"
            castShadow
            receiveShadow
            geometry={gltf.nodes.SpaceCasset_7.geometry}
            material={gltf.materials.Material}
          />
          <T.Mesh
            name="SpaceCasset_8"
            castShadow
            receiveShadow
            geometry={gltf.nodes.SpaceCasset_8.geometry}
            material={gltf.materials.circle}
          />
          <T.Mesh
            name="SpaceCasset_9"
            castShadow
            receiveShadow
            geometry={gltf.nodes.SpaceCasset_9.geometry}
            material={gltf.materials.text}
          />
        </T.Group>
      </T.Group>
      <T.Group
        name="Kirby"
        position={[1, 0.45, 2]}
        rotation={[-Math.PI, Math.PI / 6, -Math.PI]}
        scale={0.4}
        userData={{ name: 'Kirby' }}
      >
        <T.Mesh
          name="Kirby_1"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Kirby_1.geometry}
          material={gltf.materials.Kirby}
          userData={{ name: 'Kirby' }}
        />
      </T.Group>
      <T.Group
        name="Laptop"
        position={[0, 0.55, 1.85]}
        rotation={[3.12, 0.52, -3.13]}
        userData={{ name: 'Laptop' }}
      >
        <T.Group
          name="Laptop_1"
          userData={{ name: 'Laptop' }}
        >
          <T.Mesh
            name="Laptop_2"
            castShadow
            receiveShadow
            geometry={gltf.nodes.Laptop_2.geometry}
            material={gltf.materials.LaptopBase}
          />
          <T.Mesh
            name="Laptop_3"
            castShadow
            receiveShadow
            geometry={gltf.nodes.Laptop_3.geometry}
            material={gltf.materials.LaptopKeys}
          />
          <T.Mesh
            name="Laptop_4"
            castShadow
            receiveShadow
            geometry={gltf.nodes.Laptop_4.geometry}
            material={gltf.materials.LaptopTouchpad}
          />
          <T.Mesh
            name="Laptop_5"
            castShadow
            receiveShadow
            geometry={gltf.nodes.Laptop_5.geometry}
            material={gltf.materials.LaptopIntel}
          />
          <T.Mesh
            name="Laptop_6"
            castShadow
            receiveShadow
            geometry={gltf.nodes.Laptop_6.geometry}
            material={gltf.materials.LaptopDetail}
          />
          <T.Group
            name="Pad"
            userData={{ name: 'Pad' }}
          >
            <T.Mesh
              name="Cube006"
              castShadow
              receiveShadow
              geometry={gltf.nodes.Cube006.geometry}
              material={gltf.materials.LaptopBase}
            />
            <T.Mesh
              name="Cube006_1"
              castShadow
              receiveShadow
              geometry={gltf.nodes.Cube006_1.geometry}
              material={gltf.materials.LaptopKeys}
            />
            <T.Mesh
              name="Cube006_2"
              castShadow
              receiveShadow
              geometry={gltf.nodes.Cube006_2.geometry}
              material={gltf.materials.LaptopLigth}
            />
          </T.Group>
          <T.Group
            name="Screen"
            userData={{ name: 'Screen' }}
          >
            <T.Mesh
              name="Cube004"
              castShadow
              receiveShadow
              geometry={gltf.nodes.Cube004.geometry}
              material={gltf.materials.LaptopBase}
            />
            <T.Mesh
              name="Cube004_1"
              castShadow
              receiveShadow
              geometry={gltf.nodes.Cube004_1.geometry}
              material={gltf.materials.LaptopDisplay}
            />
          </T.Group>
        </T.Group>
      </T.Group>
      <T.Group
        name="SpacePanda"
        position={[-0.06, 0.56, 1.1]}
        userData={{ name: 'SpacePanda' }}
      >
        <T.Group
          name="metarig"
          userData={{ name: 'metarig' }}
        >
          <T is={gltf.nodes.spine} />
          <T.SkinnedMesh
            name="SpacePanda_1"
            castShadow
            receiveShadow
            geometry={gltf.nodes.SpacePanda_1.geometry}
            material={gltf.materials.SpacePanda}
            skeleton={gltf.nodes.SpacePanda_1.skeleton}
            userData={{ name: 'SpacePanda' }}
          />
        </T.Group>
      </T.Group>
      <T.Group
        name="Logos"
        position={[-0.45, 1.63, -2.29]}
        userData={{ name: 'Logos' }}
      >
        <T.Group
          name="GitHub"
          userData={{ name: 'GitHub' }}
        >
          <T.Mesh
            name="GitHub_1"
            castShadow
            receiveShadow
            geometry={gltf.nodes.GitHub_1.geometry}
            material={gltf.materials.GithubLogo}
          />
          <T.Mesh
            name="GitHub_2"
            castShadow
            receiveShadow
            geometry={gltf.nodes.GitHub_2.geometry}
            material={gltf.materials.LightWooden}
          />
        </T.Group>
        <T.Group
          name="Blog"
          rotation={[-Math.PI, 0, -Math.PI]}
          userData={{ name: 'Blog' }}
        >
          <T.Mesh
            name="Blog_1"
            castShadow
            receiveShadow
            geometry={gltf.nodes.Blog_1.geometry}
            material={gltf.materials.BlogLogo}
          />
          <T.Mesh
            name="Blog_2"
            castShadow
            receiveShadow
            geometry={gltf.nodes.Blog_2.geometry}
            material={gltf.materials.LightWooden}
          />
        </T.Group>
        <T.Group
          name="Twitter"
          userData={{ name: 'Twitter' }}
        >
          <T.Mesh
            name="Twitter_1"
            castShadow
            receiveShadow
            geometry={gltf.nodes.Twitter_1.geometry}
            material={gltf.materials.TwitterLogo}
          />
          <T.Mesh
            name="Twitter_2"
            castShadow
            receiveShadow
            geometry={gltf.nodes.Twitter_2.geometry}
            material={gltf.materials.LightWooden}
          />
        </T.Group>
        <T.Group
          name="LinkedIn"
          rotation={[-Math.PI, 0, -Math.PI]}
          userData={{ name: 'LinkedIn' }}
        >
          <T.Mesh
            name="LinkedIn_1"
            castShadow
            receiveShadow
            geometry={gltf.nodes.LinkedIn_1.geometry}
            material={gltf.materials.LightWooden}
          />
          <T.Mesh
            name="LinkedIn_2"
            castShadow
            receiveShadow
            geometry={gltf.nodes.LinkedIn_2.geometry}
            material={gltf.materials.LinkedInMaterial}
          />
        </T.Group>
        <T.Group
          name="Instagram"
          rotation={[-Math.PI, 0, -Math.PI]}
          userData={{ name: 'Instagram' }}
        >
          <T.Mesh
            name="Instagram_1"
            castShadow
            receiveShadow
            geometry={gltf.nodes.Instagram_1.geometry}
            material={gltf.materials.LightWooden}
          />
          <T.Mesh
            name="Instagram_2"
            castShadow
            receiveShadow
            geometry={gltf.nodes.Instagram_2.geometry}
            material={gltf.materials.InstagramLogo}
          />
        </T.Group>
      </T.Group>
      <T.Group
        name="Home"
        userData={{ name: 'Home' }}
      >
        <T.Mesh
          name="Home_1"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Home_1.geometry}
          material={gltf.materials.LeatherCracked}
        />
        <T.Mesh
          name="Home_2"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Home_2.geometry}
          material={gltf.materials.WoodDark}
        />
        <T.Mesh
          name="Home_3"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Home_3.geometry}
          material={gltf.materials.BaseWhite}
        />
        <T.Mesh
          name="Home_4"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Home_4.geometry}
          material={gltf.materials.WoodLast}
        />
        <T.Mesh
          name="Home_5"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Home_5.geometry}
          material={gltf.materials.GucciBase}
        />
        <T.Mesh
          name="Home_6"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Home_6.geometry}
          material={gltf.materials.GucciGold}
        />
        <T.Mesh
          name="Home_7"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Home_7.geometry}
          material={gltf.materials.Cartton}
        />
        <T.Mesh
          name="Home_8"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Home_8.geometry}
          material={gltf.materials.CarttonHandle}
        />
        <T.Mesh
          name="Home_9"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Home_9.geometry}
          material={gltf.materials.CarttonCap}
        />
        <T.Mesh
          name="Home_10"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Home_10.geometry}
          material={gltf.materials.TV}
        />
        <T.Mesh
          name="Home_11"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Home_11.geometry}
          material={gltf.materials.PlasticBasicBlack}
        />
        <T.Mesh
          name="Home_12"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Home_12.geometry}
          material={gltf.materials.Cover_3}
        />
        <T.Mesh
          name="Home_13"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Home_13.geometry}
          material={gltf.materials.Cover_1}
        />
        <T.Mesh
          name="Home_14"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Home_14.geometry}
          material={gltf.materials.Cover_2}
        />
        <T.Mesh
          name="Home_15"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Home_15.geometry}
          material={gltf.materials.Cover_4}
        />
        <T.Mesh
          name="Home_16"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Home_16.geometry}
          material={gltf.materials.Keyboard}
        />
        <T.Mesh
          name="Home_17"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Home_17.geometry}
          material={gltf.materials.BasePurple}
        />
        <T.Mesh
          name="Home_18"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Home_18.geometry}
          material={gltf.materials.BaseBlueTwo}
        />
        <T.Mesh
          name="Home_19"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Home_19.geometry}
          material={gltf.materials.BaseBrown}
        />
        <T.Mesh
          name="Home_20"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Home_20.geometry}
          material={gltf.materials.BigPicture}
        />
        <T.Mesh
          name="Home_21"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Home_21.geometry}
          material={gltf.materials.WoodLight}
        />
        <T.Mesh
          name="Home_22"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Home_22.geometry}
          material={gltf.materials.LampShade}
        />
        <T.Mesh
          name="Home_23"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Home_23.geometry}
          material={gltf.materials.LampBase}
        />
        <T.Mesh
          name="Home_24"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Home_24.geometry}
          material={gltf.materials.LampLigth}
        />
        <T.Mesh
          name="Home_25"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Home_25.geometry}
          material={gltf.materials.Dust}
        />
        <T.Mesh
          name="Home_26"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Home_26.geometry}
          material={gltf.materials.TextMaterial}
        />
        <T.Mesh
          name="Home_27"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Home_27.geometry}
          material={gltf.materials.Glass}
        />
        <T.Mesh
          name="Home_28"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Home_28.geometry}
          material={gltf.materials.P1SColor}
        />
        <T.Mesh
          name="Home_29"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Home_29.geometry}
          material={gltf.materials.Emission}
        />
        <T.Mesh
          name="Home_30"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Home_30.geometry}
          material={gltf.materials.FabricWeaved}
        />
        <T.Mesh
          name="Home_31"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Home_31.geometry}
          material={gltf.materials.MePicture}
        />
        <T.Mesh
          name="Home_32"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Home_32.geometry}
          material={gltf.materials.LightBase}
        />
        <T.Mesh
          name="Home_33"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Home_33.geometry}
          material={gltf.materials.StringLigth}
        />
        <T.Mesh
          name="Home_34"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Home_34.geometry}
          material={gltf.materials.BaseBlack}
        />
        <T.Mesh
          name="Home_35"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Home_35.geometry}
          material={gltf.materials.FabricWeavedDark}
        />
        <T.Mesh
          name="Home_36"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Home_36.geometry}
          material={gltf.materials.SmallPicture}
        />
        <T.Mesh
          name="Home_37"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Home_37.geometry}
          material={gltf.materials.Cactus}
        />
        <T.Mesh
          name="Home_38"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Home_38.geometry}
          material={gltf.materials['Modern Fiberstone']}
        />
        <T.Mesh
          name="Home_39"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Home_39.geometry}
          material={gltf.materials.GardenSoil}
        />
        <T.Mesh
          name="Home_40"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Home_40.geometry}
          material={gltf.materials.AuxWoodLast}
        />
        <T.Mesh
          name="Home_41"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Home_41.geometry}
          material={gltf.materials.RubberBumpy}
        />
        <T.Mesh
          name="Home_42"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Home_42.geometry}
          material={gltf.materials.AuxDisplay}
        />
      </T.Group>
      <T.Group
        name="Clock"
        position={[-1.37, 2.05, -1.13]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        userData={{ name: 'Clock' }}
      >
        <T.Mesh
          name="Plane"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Plane.geometry}
          material={gltf.materials.BaseWhite}
        />
        <T.Mesh
          name="Plane_1"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Plane_1.geometry}
          material={gltf.materials.WoodLast}
        />
        <T.Mesh
          name="Plane_2"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Plane_2.geometry}
          material={gltf.materials.ClockHour}
        />
        <T.Mesh
          name="Plane_3"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Plane_3.geometry}
          material={gltf.materials.ClockMinute}
        />
      </T.Group>
    </T.Group>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.()}
</T>
