<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0-next.11 /home/default/nodejs/me/static/models/Planet_1.gltf --root /models/ --types --keepnames --printwidth 120 --precision 2 --draco ./ --preload --suspense --isolated --transform --resolution 1024
-->

<script
  context="module"
  lang="ts"
>
  import type * as THREE from 'three'

  import type { Snippet } from 'svelte'
  import { T } from '@threlte/core'
  import { useGltf, useSuspense, useDraco } from '@threlte/extras'

  type GLTFResult = {
    nodes: {
      Planet_1: THREE.Mesh
    }
    materials: {
      Atlas: THREE.MeshStandardMaterial
    }
  }

  const load = () => {
    const suspend = useSuspense()
    return suspend(
      useGltf<GLTFResult>('/models/Planet_1-transformed.glb', { dracoLoader: useDraco() })
    )
  }

  export const preload = async () => {
    await load()
  }
</script>

<script lang="ts">
  let {
    fallback,
    error,
    children
  }: {
    children?: Snippet
    fallback?: Snippet
    error?: Snippet<[{ error: Error }]>
  } = $props()

  const gltf = load()
</script>

<T.Group dispose={false}>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Mesh
      name="Planet_1"
      geometry={gltf.nodes.Planet_1.geometry}
      material={gltf.materials.Atlas}
    />
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.()}
</T.Group>
