import * as THREE from 'three';
import { GLTFLoader, type GLTF } from 'three/examples/jsm/loaders/GLTFLoader.js';
import { DRACOLoader } from 'three/examples/jsm/loaders/DRACOLoader.js';
import { KTX2Loader } from 'three/examples/jsm/loaders/KTX2Loader.js';
import { m } from '$lib/paraglide/messages';
import { create_video_texture } from '$lib/util/video.svelte';
import { createOutlineMaterial, createSkinnedOutlineMaterial, addOutlineMesh } from '../effects/outline-hull';
import type { HomeGLTFNodes, HomeGLTFMaterials } from './home-gltf';

/** Served from this app's own static/ instead of the gstatic CDN Threlte's own useDraco() defaults to
 *  (@threlte/extras) — one less external network dependency on the model's critical load path, and lets
 *  preload() below start fetching/instantiating the decoder in parallel with the GLTF's own download
 *  instead of only starting once the model finishes and the loader is first invoked. */
const DRACO_DECODER_PATH = '/draco/';

/** The room's own textures are KTX2/Basis-Universal-compressed (see scripts/model-pipeline.ts's own
 *  comment on why) — this is the transcoder KTX2Loader needs to turn that into whatever compressed GPU
 *  texture format this device actually supports. */
const BASIS_TRANSCODER_PATH = '/basis/';

/**
 * The room model — previously `$lib/models/home.svelte` (a 1172-line file auto-generated by
 * @threlte/gltf, hand-flattening the GLTF's own node tree into one `<T.Mesh>`/`<T.Group>` per node so
 * Threlte's reactivity has something declarative to diff) plus `sceens/room.svelte`'s own
 * post-load material/animation/clock logic layered on top via `injectPlugin`.
 *
 * The codegen'd file's per-group position/rotation/scale props (e.g. `SpaceMilk` at
 * `position={[1.1, 0.9, -1.65]}`) are NOT deliberate overrides — they're the exact transform the tool
 * read off each node in the original GLTF and hoisted into JSX so Threlte could re-render it
 * declaratively. Loading `gltf.scene` directly (this file) reproduces the identical arrangement with
 * no manual re-application needed — every node already carries that same baked transform.
 */
export class Room {
	readonly group = new THREE.Group();
	/** Named node/material access, restored from the deleted Threlte-generated component's own
	 *  `nodes`/`materials` props (built here the same way drei's `useGraph`/Threlte's `useGltf` build
	 *  them: walking the loaded scene once by name) — populated once the GLTF resolves, `null` before
	 *  that. Typed against `home-gltf.ts`'s codegen-extracted shape. */
	nodes: HomeGLTFNodes | null = null;
	materials: HomeGLTFMaterials | null = null;

	private mixer: THREE.AnimationMixer | null = null;
	private hourHand: THREE.Object3D | null = null;
	private minuteHand: THREE.Object3D | null = null;
	private jointMeshes: THREE.Mesh[] = [];
	private videoDisposers: (() => void)[] = [];
	private friendly = true;
	private loadedRoot: THREE.Object3D | null = null;
	private disposed = false;

	// Meshes stay hidden until revealed a few at a time in loop() — see its own comment. A mesh only
	// triggers its material's shader compilation on its first actual draw call, so revealing all ~135 of
	// them (and their up to ~27 distinct shader programs) in the same frame means a burst of that many
	// compiles landing on the driver at once. On at least one GPU/driver that burst is what's crashing
	// the context — every other measured axis (total program count, texture memory, geometry count) came
	// back unremarkable, so it's the compile *rate* at that one moment under suspicion, not steady-state
	// load. Spreading reveal — and so compilation — across many frames tests that directly.
	private revealQueue: THREE.Mesh[] = [];
	private static readonly REVEAL_BATCH_SIZE = 1;
	private revealComplete = false;
	private onFullyRevealed?: () => void;

	// Shared across every matching mesh instead of constructing one per mesh — see setupNode(). The
	// model splits objects into one sub-mesh per material (node names like SpaceMilk_2..9,
	// SpaceJuice_2..12 are per-material submeshes of one conceptual object), so a naive one-material-
	// per-mesh approach here means one *separate* transmissive material per glass submesh. Three.js's
	// WebGLRenderer runs a whole extra "transmission buffer" render pass per unique transmissive
	// material every frame — a dozen-plus separate glass materials means a dozen-plus extra passes,
	// real GPU load with nothing to do with anything else in this file.
	private readonly glassMaterial = new THREE.MeshPhysicalMaterial({
		transmission: 1,
		opacity: 1,
		color: 0xfbfbfb,
		metalness: 0,
		roughness: 0,
		ior: 3,
		thickness: 0.01,
		specularIntensity: 1,
		envMapIntensity: 1,
		depthWrite: false,
		specularColor: new THREE.Color(0xfbfbfb)
	});
	private readonly waterMaterial = new THREE.MeshBasicMaterial({
		color: 0x558bc8,
		transparent: true,
		opacity: 0.4,
		depthWrite: false
	});

	// The one material that's consistently caused the real context-loss crash — confirmed via
	// gpu-diagnostics.ts's own renderer.info snapshot, taken right at the moment of an actual
	// CONTEXT_LOST_WEBGL, across multiple runs at different REVEAL_BATCH_SIZE values (6, then 1): every
	// time, "LeatherCracked" was the only room-specific material in the (otherwise tiny, 5-6 program)
	// list, and its own program was the last thing to compile before the context died. Landing on the
	// exact same material at two very different reveal *rates* rules out a generic burst/timing trigger
	// — this material's own compiled shader is what breaks this GPU/driver. No texture maps on the
	// original (confirmed via gpu-diagnostics.ts's own texture scan — it never appears there), so
	// whatever's wrong is in its own feature/define combination, not a missing-attribute mismatch. A
	// flat, mapless MeshStandardMaterial sidesteps it entirely without knowing the exact cause.
	private readonly leatherCrackedMaterial = new THREE.MeshStandardMaterial({
		color: 0x4a3728,
		roughness: 0.85,
		metalness: 0
	});

	/** One shared inverted-hull outline material for every ordinary mesh in the room, plus a second
	 *  one for skinned/rigged meshes (the astronaut panda) — see outline-hull.ts's own comment for why
	 *  one shared program each instead of one per mesh. */
	private readonly outlineMaterial = createOutlineMaterial();
	private readonly outlineMaterialSkinned = createSkinnedOutlineMaterial();

	private ktx2Loader: KTX2Loader;

	/** `onFullyRevealed` fires once every mesh has been unhidden (and so had its material's shader
	 *  compiled — see revealQueue's own comment) — the actual "the room is ready to look at" moment,
	 *  later than the GLTF finishing its network fetch/parse. Used to drive a loading UI (see
	 *  routes/home/+page.svelte). */
	constructor(renderer: THREE.WebGLRenderer, onFullyRevealed?: () => void) {
		this.onFullyRevealed = onFullyRevealed;
		this.group.name = 'Room';

		const draco = new DRACOLoader();
		draco.setDecoderPath(DRACO_DECODER_PATH);
		// Starts fetching/instantiating the decoder WASM right away instead of waiting for the GLTF's
		// own network fetch to finish first and only then loading the decoder on first use — the two
		// downloads now happen in parallel.
		draco.preload();

		this.ktx2Loader = new KTX2Loader();
		this.ktx2Loader.setTranscoderPath(BASIS_TRANSCODER_PATH);
		// Needs the actual renderer to know which compressed GPU texture format (BC7/ASTC/ETC1/etc.)
		// this device supports transcoding to.
		this.ktx2Loader.detectSupport(renderer);

		const loader = new GLTFLoader();
		loader.setDRACOLoader(draco);
		loader.setKTX2Loader(this.ktx2Loader);

		// Dev-only — this is the single longest thing /home does at startup (network fetch + Draco
		// decode + parse of a ~1.9MB glb), and being async it can't be captured by timing the
		// constructor call itself (see home-scene.ts's own timeStep() around `new Room()`).
		if (import.meta.env.DEV) console.time('[timing] Room GLTF load');

		loader.load(
			m['assets.home_model'](),
			(gltf) => this.onLoad(gltf),
			undefined,
			(err) => console.error('[Room] failed to load GLTF:', err)
		);
	}

	private onLoad(gltf: GLTF): void {
		// Constructed between the load starting and finishing — bail if dispose() already ran.
		if (this.disposed) return;

		this.loadedRoot = gltf.scene;
		this.group.add(gltf.scene);

		if (gltf.animations.length > 0) {
			this.mixer = new THREE.AnimationMixer(gltf.scene);
			// Matches sceens/room.svelte's own $effect: slowed to 40% speed, every clip auto-playing.
			this.mixer.timeScale = 0.4;
			for (const clip of gltf.animations) this.mixer.clipAction(clip).play();
		}

		const nodes: Record<string, THREE.Object3D> = {};
		const materials: Record<string, THREE.Material> = {};
		const meshes: THREE.Mesh[] = [];

		gltf.scene.traverse((obj) => {
			// setupNode() below adds an outline mesh as a child of `obj` — traverse() re-reads each
			// node's own `children` right after visiting it, so that outline mesh gets visited by this
			// same traversal too. Skip it here: it's not a real room node/mesh, it shouldn't get its own
			// revealQueue slot (see outline-hull.ts's own comment — it inherits visibility from its
			// parent for free, so batching it separately just wastes reveal frames).
			if (obj.userData.isOutlineHull) return;

			if (obj.name) nodes[obj.name] = obj;
			// Captured before setupNode() runs — it swaps `.material` outright for glass/water/tv/
			// auxdisplay meshes, and the replacement has no `.name` of its own.
			if (obj instanceof THREE.Mesh && obj.material) {
				const mat = obj.material as THREE.Material;
				if (mat.name) materials[mat.name] = mat;
				meshes.push(obj);
			}
			this.setupNode(obj);
		});

		this.nodes = nodes as unknown as HomeGLTFNodes;
		this.materials = materials as unknown as HomeGLTFMaterials;

		// Hide everything, then let loop() reveal it a few meshes at a time — see revealQueue's own
		// comment. Not applyFriendlyVisibility() here: each mesh gets its correct final visibility
		// (joint meshes respecting `this.friendly`, everything else just visible) computed at the moment
		// it's actually revealed, in revealNextBatch(), so this initial pass only needs to hide.
		for (const mesh of meshes) mesh.visible = false;
		this.revealQueue = meshes;

		if (import.meta.env.DEV) {
			console.timeEnd('[timing] Room GLTF load');
			// How many meshes each substring match covers — the glass/water counts are exactly what
			// would have flagged the transmission-material bug immediately (see glassMaterial's own
			// comment above): a large count sharing ONE material is fine, that same count each getting
			// its own material is a dozen-plus redundant render passes.
			const counts = Array.from(this.classificationCounts, ([label, n]) => `${label}: ${n}`).join(', ');
			console.log(`[gpu] Room mesh classification counts: ${counts || '(none)'}`);
		}
	}

	/** Ported from sceens/room.svelte's own change_obj() — material swaps and named-mesh references,
	 *  matched by material/mesh name substring exactly as that file did. */
	private setupNode(obj: THREE.Object3D): void {
		// gltf.scene.traverse() re-reads each node's own `children` right after invoking this callback
		// on it — so an outline mesh added below (as a child of `obj`) gets visited by that same
		// traversal too. Without this guard, setupNode would run on the outline mesh, add another
		// outline as ITS child, get traversed into, and so on forever.
		if (obj.userData.isOutlineHull) return;
		if (!(obj instanceof THREE.Mesh) || !obj.material) return;

		obj.castShadow = true;
		obj.receiveShadow = true;

		const material = obj.material as THREE.Material;
		const name = (material.name ?? '').toLowerCase();

		if (name.includes('joint')) {
			this.jointMeshes.push(obj);
			this.countClassification('joint');
		}

		if (name.includes('leathercracked')) {
			obj.material = this.leatherCrackedMaterial;
			this.countClassification('leathercracked (substitute material — see its own comment)');
		} else if (name.includes('glass')) {
			obj.material = this.glassMaterial;
			this.countClassification('glass (shared material)');
		} else if (name.includes('water')) {
			obj.material = this.waterMaterial;
			this.countClassification('water (shared material)');
		} else if (name.includes('tv')) {
			const { texture, dispose } = create_video_texture(m['assets.room_screen_video']());
			this.videoDisposers.push(dispose);
			obj.material = new THREE.MeshBasicMaterial({ map: texture, name: 'tv', transparent: true, opacity: 0.9 });
			this.countClassification('tv (own material each — video texture, expected)');
		} else if (name.includes('auxdisplay')) {
			const { texture, dispose } = create_video_texture(m['assets.room_music_player_video']());
			this.videoDisposers.push(dispose);
			obj.material = new THREE.MeshBasicMaterial({ map: texture, name: 'aux', transparent: true, opacity: 0.9 });
			this.countClassification('auxdisplay (own material each — video texture, expected)');
		}

		if (name.includes('hour')) this.hourHand = obj;
		if (name.includes('minute')) this.minuteHand = obj;

		// Skip flat video-screen meshes (tv/auxdisplay) — inverted-hull only reads as an outline on a
		// mesh with actual volume (curved/closed geometry gives it back faces that poke out past the
		// silhouette at grazing angles); a screen is a thin, effectively flat quad, so the "outline"
		// there is really the WHOLE extruded copy sitting just in front of/behind the video plane,
		// reading as a solid border that shrinks the visible video into the screen's frame. Also skip
		// glass/water: both use `depthWrite: false` (see their own materials above) so the depth buffer
		// never gets the real mesh's depth to correctly occlude the outline's extruded back faces
		// against, which can make the outline render wrong (visible where it shouldn't be) instead of
		// just tracing the silhouette.
		const skipOutline =
			name.includes('tv') || name.includes('auxdisplay') || name.includes('glass') || name.includes('water');
		if (!skipOutline) addOutlineMesh(obj, this.outlineMaterial, this.outlineMaterialSkinned);
	}

	private classificationCounts = new Map<string, number>();

	private countClassification(label: string): void {
		if (!import.meta.env.DEV) return;
		this.classificationCounts.set(label, (this.classificationCounts.get(label) ?? 0) + 1);
	}

	/** "Safe mode" — hides the model's own joint/rig meshes when friendly mode is ON (the site's
	 *  default), matching sceens/room.svelte's own `obj.visible = !friendly.value` per joint mesh. */
	setFriendly(friendly: boolean): void {
		this.friendly = friendly;
		this.applyFriendlyVisibility();
	}

	private applyFriendlyVisibility(): void {
		for (const mesh of this.jointMeshes) mesh.visible = !this.friendly;
	}

	/** Reveals the next REVEAL_BATCH_SIZE hidden meshes (each getting its correct final visibility, not
	 *  just `true` — a joint mesh stays hidden if friendly mode is currently on) — see revealQueue's own
	 *  comment for why this exists at all instead of just unhiding everything at once. Fires
	 *  onFullyRevealed() exactly once, the frame the queue first empties. Guarded on `loadedRoot` so it
	 *  can't fire before the GLTF has even loaded — before that, the queue is empty too, for a completely
	 *  different reason (nothing to reveal yet, not "done revealing"). */
	private revealNextBatch(): void {
		if (this.loadedRoot === null) return;

		if (this.revealQueue.length === 0) {
			if (!this.revealComplete) {
				this.revealComplete = true;
				this.onFullyRevealed?.();
			}
			return;
		}

		const batch = this.revealQueue.splice(0, Room.REVEAL_BATCH_SIZE);
		for (const mesh of batch) {
			mesh.visible = this.jointMeshes.includes(mesh) ? !this.friendly : true;
		}
	}

	/** Called every frame — advances the animation mixer and points the clock hands at the current
	 *  time (sceens/room.svelte's own two $effects, folded into one per-frame update instead of a
	 *  1-minute setInterval — cheap enough to just recompute live, and avoids the up-to-60s-stale
	 *  hand position the interval version could show right after a page load). */
	loop(delta: number): void {
		this.revealNextBatch();
		this.mixer?.update(delta);

		if (this.hourHand && this.minuteHand) {
			const now = new Date();
			const hours = now.getHours() % 12;
			const minutes = now.getMinutes();
			const seconds = now.getSeconds();
			const minuteAngle = (minutes + seconds / 60) * ((Math.PI * 2) / 60);
			const hourAngle = (hours + minutes / 60) * ((Math.PI * 2) / 12);
			this.minuteHand.rotation.y = -minuteAngle;
			this.hourHand.rotation.y = -hourAngle;
		}
	}

	/** Ported from sceens/room.svelte's own dispose_node() — recursively frees geometry, every
	 *  material (and any texture assigned to it), for the whole loaded subtree. */
	dispose(): void {
		this.disposed = true;
		this.videoDisposers.forEach((d) => d());
		this.ktx2Loader.dispose();
		if (this.loadedRoot) this.disposeNode(this.loadedRoot);
		this.outlineMaterial.dispose();
		this.outlineMaterialSkinned.dispose();
	}

	private disposeNode(node: THREE.Object3D): void {
		for (const child of node.children) this.disposeNode(child);

		// Outline meshes share both their geometry (the mesh they're a child of already disposes it)
		// and their material (one shared instance across the whole room, disposed once in dispose()
		// above) — nothing here is actually owned by this node.
		if (node.userData.isOutlineHull) return;

		if (node instanceof THREE.Mesh) {
			node.geometry?.dispose();
			const materials = Array.isArray(node.material) ? node.material : [node.material];
			for (const mat of materials) {
				if (!mat) continue;
				for (const key of Object.keys(mat)) {
					const value = (mat as unknown as Record<string, unknown>)[key];
					if (value && typeof value === 'object' && (value as THREE.Texture).isTexture) {
						(value as THREE.Texture).dispose();
					}
				}
				mat.dispose();
			}
		}
	}
}
