<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0-next.11 /home/default/node/me/static/models/astroid.glb --root /models/ --keepnames --meta --shadows --printwidth 120 --precision 2 --draco ./ --preload --suspense --isolated --transform --resolution 1024 --simplify --weld 0.0001 --ratio 0.75 --error 0.001
-->

<script context="module">
  import { Group } from 'three'

  import { T } from '@threlte/core'
  import { useGltf, useGltfAnimations, useSuspense, useDraco } from '@threlte/extras'

  const load = () => {
    const suspend = useSuspense()
    return suspend(useGltf('/models/astroid-transformed.glb', { dracoLoader: useDraco() }))
  }

  export const preload = async () => {
    await load()
  }
</script>

<script>
  let { fallback, error, children } = $props()

  const ref = new Group()

  const gltf = load()

  export const { actions, mixer } = useGltfAnimations(gltf, ref)
</script>

<T
  is={ref}
  dispose={false}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Group name="Scene">
      <T.Group
        name="Home"
        userData={{ name: 'Home' }}
      >
        <T.Mesh
          name="Plane004"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Plane004.geometry}
          material={gltf.materials.SandRough}
        />
        <T.Mesh
          name="Plane004_1"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Plane004_1.geometry}
          material={gltf.materials.SandRough}
        />
        <T.Mesh
          name="Plane004_2"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Plane004_2.geometry}
          material={gltf.materials.StylisedWater}
        />
        <T.Mesh
          name="Plane004_3"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Plane004_3.geometry}
          material={gltf.materials.SandRough}
        />
        <T.Mesh
          name="Plane004_4"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Plane004_4.geometry}
          material={gltf.materials.Lava}
        />
        <T.Mesh
          name="Plane004_5"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Plane004_5.geometry}
          material={gltf.materials.SandRough}
        />
        <T.Mesh
          name="Plane004_6"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Plane004_6.geometry}
          material={gltf.materials.SandRough}
        />
        <T.Mesh
          name="Plane004_7"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Plane004_7.geometry}
          material={gltf.materials.SandRough}
        />
        <T.Mesh
          name="Plane004_8"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Plane004_8.geometry}
          material={gltf.materials.SandRough}
        />
        <T.Mesh
          name="Plane004_9"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Plane004_9.geometry}
          material={gltf.materials.Glass}
        />
        <T.Mesh
          name="Plane004_10"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Plane004_10.geometry}
          material={gltf.materials.Glass}
        />
        <T.Mesh
          name="Plane004_11"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Plane004_11.geometry}
          material={gltf.materials.SandRough}
        />
        <T.Mesh
          name="Plane004_12"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Plane004_12.geometry}
          material={gltf.materials.SandRough}
        />
        <T.Mesh
          name="Plane004_13"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Plane004_13.geometry}
          material={gltf.materials.Emission}
        />
        <T.Mesh
          name="Plane004_14"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Plane004_14.geometry}
          material={gltf.materials.SandRough}
        />
        <T.Mesh
          name="Plane004_15"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Plane004_15.geometry}
          material={gltf.materials.Vine}
        />
        <T.Mesh
          name="Plane004_16"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Plane004_16.geometry}
          material={gltf.materials['LeafSet029_1K-JPG_Color']}
        />
        <T.Mesh
          name="Plane004_17"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Plane004_17.geometry}
          material={gltf.materials.SandRough}
        />
        <T.Mesh
          name="Plane004_18"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Plane004_18.geometry}
          material={gltf.materials['Modern Fiberstone']}
        />
        <T.Mesh
          name="Plane004_19"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Plane004_19.geometry}
          material={gltf.materials.SandRough}
        />
        <T.Mesh
          name="Plane004_20"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Plane004_20.geometry}
          material={gltf.materials.SandRough}
        />
        <T.Mesh
          name="Plane004_21"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Plane004_21.geometry}
          material={gltf.materials.SandRough}
        />
        <T.Mesh
          name="Plane004_22"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Plane004_22.geometry}
          material={gltf.materials.SandRough}
        />
        <T.Mesh
          name="Plane004_23"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Plane004_23.geometry}
          material={gltf.materials.SandRough}
        />
        <T.Mesh
          name="Plane004_24"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Plane004_24.geometry}
          material={gltf.materials.FabricWeavedDark}
        />
        <T.Mesh
          name="Plane004_25"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Plane004_25.geometry}
          material={gltf.materials.FabricWeavedDark}
        />
        <T.Mesh
          name="Plane004_26"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Plane004_26.geometry}
          material={gltf.materials.SandRough}
        />
      </T.Group>
    </T.Group>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.()}
</T>
