<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0-next.11 /home/default/node/me/static/models/cassette.glb --root /models/ --keepnames --meta --shadows --printwidth 120 --precision 2 --draco ./ --preload --suspense --isolated --transform --resolution 1024 --simplify --weld 0.0001 --ratio 0.75 --error 0.001
-->

<script context="module">
  import { T } from '@threlte/core'
  import { useGltf, useSuspense, useDraco } from '@threlte/extras'

  const load = () => {
    const suspend = useSuspense()
    return suspend(useGltf('/models/cassette-transformed.glb', { dracoLoader: useDraco() }))
  }

  export const preload = async () => {
    await load()
  }
</script>

<script>
  let { fallback, error, children } = $props()

  const gltf = load()
</script>

<T.Group dispose={false}>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Group
      name="SpaceCasset"
      userData={{ name: 'SpaceCasset' }}
    >
      <T.Mesh
        name="Plane"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Plane.geometry}
        material={gltf.materials.Render}
      />
      <T.Mesh
        name="Plane_1"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Plane_1.geometry}
        material={gltf.materials.star_1}
      />
      <T.Mesh
        name="Plane_2"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Plane_2.geometry}
        material={gltf.materials.star_2}
      />
      <T.Mesh
        name="Plane_3"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Plane_3.geometry}
        material={gltf.materials.transparent}
      />
      <T.Mesh
        name="Plane_4"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Plane_4.geometry}
        material={gltf.materials.metal_refl}
      />
      <T.Mesh
        name="Plane_5"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Plane_5.geometry}
        material={gltf.materials['dark purple']}
      />
      <T.Mesh
        name="Plane_6"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Plane_6.geometry}
        material={gltf.materials.outline}
      />
      <T.Mesh
        name="Plane_7"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Plane_7.geometry}
        material={gltf.materials.Material}
      />
      <T.Mesh
        name="Plane_8"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Plane_8.geometry}
        material={gltf.materials.circle}
      />
      <T.Mesh
        name="Plane_9"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Plane_9.geometry}
        material={gltf.materials.text}
      />
    </T.Group>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.()}
</T.Group>
