<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0-next.11 /home/default/node/me/static/models/juice.glb --root /models/ --keepnames --meta --shadows --printwidth 120 --precision 2 --draco ./ --preload --suspense --isolated --transform --resolution 1024 --simplify --weld 0.0001 --ratio 0.75 --error 0.001
-->

<script context="module">
  import { T } from '@threlte/core'
  import { useGltf, useSuspense, useDraco } from '@threlte/extras'

  const load = () => {
    const suspend = useSuspense()
    return suspend(useGltf('/models/juice-transformed.glb', { dracoLoader: useDraco() }))
  }

  export const preload = async () => {
    await load()
  }
</script>

<script>
  let { fallback, error, children } = $props()

  const gltf = load()
</script>

<T.Group dispose={false}>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Group
      name="SpaceJuice"
      userData={{ name: 'SpaceJuice' }}
    >
      <T.Mesh
        name="SpaceJuice_1"
        castShadow
        receiveShadow
        geometry={gltf.nodes.SpaceJuice_1.geometry}
        material={gltf.materials.liquid}
      />
      <T.Mesh
        name="SpaceJuice_2"
        castShadow
        receiveShadow
        geometry={gltf.nodes.SpaceJuice_2.geometry}
        material={gltf.materials.liquidtop}
      />
      <T.Mesh
        name="SpaceJuice_3"
        castShadow
        receiveShadow
        geometry={gltf.nodes.SpaceJuice_3.geometry}
        material={gltf.materials['Outline.001']}
      />
      <T.Mesh
        name="SpaceJuice_4"
        castShadow
        receiveShadow
        geometry={gltf.nodes.SpaceJuice_4.geometry}
        material={gltf.materials.box_base}
      />
      <T.Mesh
        name="SpaceJuice_5"
        castShadow
        receiveShadow
        geometry={gltf.nodes.SpaceJuice_5.geometry}
        material={gltf.materials.IMG_1142}
      />
      <T.Mesh
        name="SpaceJuice_6"
        castShadow
        receiveShadow
        geometry={gltf.nodes.SpaceJuice_6.geometry}
        material={gltf.materials.Material}
      />
      <T.Mesh
        name="SpaceJuice_7"
        castShadow
        receiveShadow
        geometry={gltf.nodes.SpaceJuice_7.geometry}
        material={gltf.materials['light green layerweight']}
      />
      <T.Mesh
        name="SpaceJuice_8"
        castShadow
        receiveShadow
        geometry={gltf.nodes.SpaceJuice_8.geometry}
        material={gltf.materials['Outline.003']}
      />
      <T.Mesh
        name="SpaceJuice_9"
        castShadow
        receiveShadow
        geometry={gltf.nodes.SpaceJuice_9.geometry}
        material={gltf.materials.dots}
      />
      <T.Mesh
        name="SpaceJuice_10"
        castShadow
        receiveShadow
        geometry={gltf.nodes.SpaceJuice_10.geometry}
        material={gltf.materials['dark purple line']}
      />
      <T.Mesh
        name="SpaceJuice_11"
        castShadow
        receiveShadow
        geometry={gltf.nodes.SpaceJuice_11.geometry}
        material={gltf.materials.recyclabe}
      />
      <T.Mesh
        name="SpaceJuice_12"
        castShadow
        receiveShadow
        geometry={gltf.nodes.SpaceJuice_12.geometry}
        material={gltf.materials.bubbles}
      />
      <T.Mesh
        name="SpaceJuice_13"
        castShadow
        receiveShadow
        geometry={gltf.nodes.SpaceJuice_13.geometry}
        material={gltf.materials.white}
      />
      <T.Mesh
        name="SpaceJuice_14"
        castShadow
        receiveShadow
        geometry={gltf.nodes.SpaceJuice_14.geometry}
        material={gltf.materials.dark_orange}
      />
      <T.Mesh
        name="SpaceJuice_15"
        castShadow
        receiveShadow
        geometry={gltf.nodes.SpaceJuice_15.geometry}
        material={gltf.materials['light orange transparent']}
      />
    </T.Group>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.()}
</T.Group>
