<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0-next.11 /home/default/node/me/static/models/milk.glb --root /models/ --keepnames --meta --shadows --printwidth 120 --precision 2 --draco ./ --preload --suspense --isolated --transform --resolution 1024 --simplify --weld 0.0001 --ratio 0.75 --error 0.001
-->

<script context="module">
  import { T } from '@threlte/core'
  import { useGltf, useSuspense, useDraco } from '@threlte/extras'

  const load = () => {
    const suspend = useSuspense()
    return suspend(useGltf('/models/milk-transformed.glb', { dracoLoader: useDraco() }))
  }

  export const preload = async () => {
    await load()
  }
</script>

<script>
  let { fallback, error, children } = $props()

  const gltf = load()
</script>

<T.Group dispose={false}>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Group
      name="SpaceMilk"
      userData={{ name: 'SpaceMilk' }}
    >
      <T.Mesh
        name="SpaceMilk_1"
        castShadow
        receiveShadow
        geometry={gltf.nodes.SpaceMilk_1.geometry}
        material={gltf.materials.spacemilk}
      />
      <T.Mesh
        name="SpaceMilk_2"
        castShadow
        receiveShadow
        geometry={gltf.nodes.SpaceMilk_2.geometry}
        material={gltf.materials.lightpink}
      />
      <T.Mesh
        name="SpaceMilk_3"
        castShadow
        receiveShadow
        geometry={gltf.nodes.SpaceMilk_3.geometry}
        material={gltf.materials['Material.004']}
      />
      <T.Mesh
        name="SpaceMilk_4"
        castShadow
        receiveShadow
        geometry={gltf.nodes.SpaceMilk_4.geometry}
        material={gltf.materials['lightpurple gradient edge']}
      />
      <T.Mesh
        name="SpaceMilk_5"
        castShadow
        receiveShadow
        geometry={gltf.nodes.SpaceMilk_5.geometry}
        material={gltf.materials['magic gradient']}
      />
      <T.Mesh
        name="SpaceMilk_6"
        castShadow
        receiveShadow
        geometry={gltf.nodes.SpaceMilk_6.geometry}
        material={gltf.materials['translucent top']}
      />
      <T.Mesh
        name="SpaceMilk_7"
        castShadow
        receiveShadow
        geometry={gltf.nodes.SpaceMilk_7.geometry}
        material={gltf.materials['purple gradient']}
      />
      <T.Mesh
        name="SpaceMilk_8"
        castShadow
        receiveShadow
        geometry={gltf.nodes.SpaceMilk_8.geometry}
        material={gltf.materials['Material.002']}
      />
      <T.Mesh
        name="SpaceMilk_9"
        castShadow
        receiveShadow
        geometry={gltf.nodes.SpaceMilk_9.geometry}
        material={gltf.materials['wawe_planet:purple']}
      />
      <T.Mesh
        name="SpaceMilk_10"
        castShadow
        receiveShadow
        geometry={gltf.nodes.SpaceMilk_10.geometry}
        material={gltf.materials.Render}
      />
      <T.Mesh
        name="SpaceMilk_11"
        castShadow
        receiveShadow
        geometry={gltf.nodes.SpaceMilk_11.geometry}
        material={gltf.materials.orange}
      />
      <T.Mesh
        name="SpaceMilk_12"
        castShadow
        receiveShadow
        geometry={gltf.nodes.SpaceMilk_12.geometry}
        material={gltf.materials['purple ring']}
      />
      <T.Mesh
        name="SpaceMilk_13"
        castShadow
        receiveShadow
        geometry={gltf.nodes.SpaceMilk_13.geometry}
        material={gltf.materials.stars}
      />
      <T.Mesh
        name="SpaceMilk_14"
        castShadow
        receiveShadow
        geometry={gltf.nodes.SpaceMilk_14.geometry}
        material={gltf.materials.meshblack}
      />
      <T.Mesh
        name="SpaceMilk_15"
        castShadow
        receiveShadow
        geometry={gltf.nodes.SpaceMilk_15.geometry}
        material={gltf.materials.meshblack}
      />
    </T.Group>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.()}
</T.Group>
