<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0-next.11 /home/default/node/me/static/models/potion.glb --root /models/ --keepnames --meta --shadows --printwidth 120 --precision 2 --draco ./ --preload --suspense --isolated --transform --resolution 1024 --simplify --weld 0.0001 --ratio 0.75 --error 0.001
-->

<script context="module">
  import { T } from '@threlte/core'
  import { useGltf, useSuspense, useDraco } from '@threlte/extras'

  const load = () => {
    const suspend = useSuspense()
    return suspend(useGltf('/models/potion-transformed.glb', { dracoLoader: useDraco() }))
  }

  export const preload = async () => {
    await load()
  }
</script>

<script>
  let { fallback, error, children } = $props()

  const gltf = load()
</script>

<T.Group dispose={false}>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Group
      name="SpacePotion"
      userData={{ name: 'SpacePotion' }}
    >
      <T.Mesh
        name="SpacePotion_1"
        castShadow
        receiveShadow
        geometry={gltf.nodes.SpacePotion_1.geometry}
        material={gltf.materials['liquid outline cork']}
      />
      <T.Mesh
        name="SpacePotion_2"
        castShadow
        receiveShadow
        geometry={gltf.nodes.SpacePotion_2.geometry}
        material={gltf.materials.rendered}
      />
      <T.Mesh
        name="SpacePotion_3"
        castShadow
        receiveShadow
        geometry={gltf.nodes.SpacePotion_3.geometry}
        material={gltf.materials.reflection}
      />
      <T.Mesh
        name="SpacePotion_4"
        castShadow
        receiveShadow
        geometry={gltf.nodes.SpacePotion_4.geometry}
        material={gltf.materials['liquid outline']}
      />
      <T.Mesh
        name="SpacePotion_5"
        castShadow
        receiveShadow
        geometry={gltf.nodes.SpacePotion_5.geometry}
        material={gltf.materials['liquid outline']}
      />
      <T.Mesh
        name="SpacePotion_6"
        castShadow
        receiveShadow
        geometry={gltf.nodes.SpacePotion_6.geometry}
        material={gltf.materials.glass}
      />
      <T.Mesh
        name="SpacePotion_7"
        castShadow
        receiveShadow
        geometry={gltf.nodes.SpacePotion_7.geometry}
        material={gltf.materials.cork}
      />
      <T.Mesh
        name="SpacePotion_8"
        castShadow
        receiveShadow
        geometry={gltf.nodes.SpacePotion_8.geometry}
        material={gltf.materials['space liquid']}
      />
      <T.Mesh
        name="SpacePotion_9"
        castShadow
        receiveShadow
        geometry={gltf.nodes.SpacePotion_9.geometry}
        material={gltf.materials.glow}
      />
      <T.Mesh
        name="SpacePotion_10"
        castShadow
        receiveShadow
        geometry={gltf.nodes.SpacePotion_10.geometry}
        material={gltf.materials.simpleplanets}
      />
      <T.Mesh
        name="SpacePotion_11"
        castShadow
        receiveShadow
        geometry={gltf.nodes.SpacePotion_11.geometry}
        material={gltf.materials.ringdarker}
      />
    </T.Group>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.()}
</T.Group>
