<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0-next.11 /home/default/node/me/static/models/speaker.glb --root /models/ --keepnames --meta --shadows --printwidth 120 --precision 2 --draco ./ --preload --suspense --isolated --transform --resolution 1024 --simplify --weld 0.0001 --ratio 0.75 --error 0.001
-->

<script context="module">
  import { Group } from 'three'

  import { T } from '@threlte/core'
  import { useGltf, useGltfAnimations, useSuspense, useDraco } from '@threlte/extras'

  const load = () => {
    const suspend = useSuspense()
    return suspend(useGltf('/models/speaker-transformed.glb', { dracoLoader: useDraco() }))
  }

  export const preload = async () => {
    await load()
  }
</script>

<script>
  let { fallback, error, children } = $props()

  const ref = new Group()

  const gltf = load()

  export const { actions, mixer } = useGltfAnimations(gltf, ref)
</script>

<T
  is={ref}
  dispose={false}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Group name="Scene">
      <T.Group
        name="bubles"
        userData={{ name: 'bubles' }}
      >
        <T.Mesh
          name="Cube017"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Cube017.geometry}
          material={gltf.materials.spheres_1}
        />
        <T.Mesh
          name="Cube017_1"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Cube017_1.geometry}
          material={gltf.materials.spheres_2}
        />
        <T.Mesh
          name="Cube017_2"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Cube017_2.geometry}
          material={gltf.materials.spheres_3}
        />
        <T.Mesh
          name="Cube017_3"
          castShadow
          receiveShadow
          geometry={gltf.nodes.Cube017_3.geometry}
          material={gltf.materials.spheres_4}
        />
      </T.Group>
      <T.Mesh
        name="Sphere003"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Sphere003.geometry}
        material={gltf.materials.musicnotes_4}
        userData={{ name: 'Sphere.003' }}
      />
      <T.Mesh
        name="Sphere004"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Sphere004.geometry}
        material={gltf.materials.musicnotes_1}
        userData={{ name: 'Sphere.004' }}
      />
      <T.Mesh
        name="Sphere005"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Sphere005.geometry}
        material={gltf.materials.musicnotes_2}
        userData={{ name: 'Sphere.005' }}
      />
      <T.Mesh
        name="Sphere006"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Sphere006.geometry}
        material={gltf.materials.musicnotes_3}
        userData={{ name: 'Sphere.006' }}
      />
      <T.Mesh
        name="Sphere007"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Sphere007.geometry}
        material={gltf.materials.musicnotes_4}
        userData={{ name: 'Sphere.007' }}
      />
      <T.Mesh
        name="Sphere008"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Sphere008.geometry}
        material={gltf.materials.musicnotes_5}
        userData={{ name: 'Sphere.008' }}
      />
      <T.Mesh
        name="NurbsPath"
        castShadow
        receiveShadow
        geometry={gltf.nodes.NurbsPath.geometry}
        material={gltf.materials.musicnotes_3}
        userData={{ name: 'NurbsPath' }}
      />
      <T.Mesh
        name="NurbsPath003"
        castShadow
        receiveShadow
        geometry={gltf.nodes.NurbsPath003.geometry}
        material={gltf.materials.musicnotes_5}
        userData={{ name: 'NurbsPath.003' }}
      />
      <T.Mesh
        name="Star017"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Star017.geometry}
        material={gltf.materials.star}
        userData={{ name: 'Star.017' }}
      />
      <T.Mesh
        name="Star001"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Star001.geometry}
        material={gltf.materials.star}
        userData={{ name: 'Star.001' }}
      />
      <T.Mesh
        name="Star003"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Star003.geometry}
        material={gltf.materials.star}
        userData={{ name: 'Star.003' }}
      />
      <T.Mesh
        name="flashes"
        castShadow
        receiveShadow
        geometry={gltf.nodes.flashes.geometry}
        material={gltf.materials.outline}
        userData={{ name: 'flashes' }}
      />
      <T.Mesh
        name="Cube007"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cube007.geometry}
        material={gltf.materials['highlights side']}
        userData={{ name: 'Cube.007' }}
      />
      <T.Mesh
        name="Cube008"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cube008.geometry}
        material={gltf.materials['highlights top']}
        userData={{ name: 'Cube.008' }}
      />
      <T.Mesh
        name="Cube"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cube.geometry}
        material={gltf.materials.magic}
        userData={{ name: 'Cube' }}
      />
      <T.Mesh
        name="Circle"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Circle.geometry}
        material={gltf.materials.bass}
        userData={{ name: 'Circle' }}
      />
      <T.Mesh
        name="Circle001"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Circle001.geometry}
        material={gltf.materials.bass}
        userData={{ name: 'Circle.001' }}
      />
      <T.Mesh
        name="Roundcube"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Roundcube.geometry}
        material={gltf.materials.bass}
        userData={{ name: 'Roundcube' }}
      />
      <T.Mesh
        name="Roundcube001"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Roundcube001.geometry}
        material={gltf.materials.bass}
        userData={{ name: 'Roundcube.001' }}
      />
      <T.Mesh
        name="Circle006"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Circle006.geometry}
        material={gltf.materials.magic}
        userData={{ name: 'Circle.006' }}
      />
      <T.Mesh
        name="Circle007"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Circle007.geometry}
        material={gltf.materials['liquid.001']}
        userData={{ name: 'Circle.007' }}
      />
      <T.Mesh
        name="Cube006"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cube006.geometry}
        material={gltf.materials.bottom}
        userData={{ name: 'Cube.006' }}
      />
      <T.Mesh
        name="Cube005"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cube005.geometry}
        material={gltf.materials.outline}
        userData={{ name: 'Cube.005' }}
      />
      <T.Mesh
        name="Circle002"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Circle002.geometry}
        material={gltf.materials.outline}
        userData={{ name: 'Circle.002' }}
      />
      <T.Mesh
        name="Circle003"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Circle003.geometry}
        material={gltf.materials.outline}
        userData={{ name: 'Circle.003' }}
      />
      <T.Mesh
        name="Circle008"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Circle008.geometry}
        material={gltf.materials.outline}
        userData={{ name: 'Circle.008' }}
      />
      <T.Mesh
        name="Circle009"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Circle009.geometry}
        material={gltf.materials.outline}
        userData={{ name: 'Circle.009' }}
      />
      <T.Mesh
        name="Circle010"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Circle010.geometry}
        material={gltf.materials.outline}
        userData={{ name: 'Circle.010' }}
      />
      <T.Mesh
        name="Cube003"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cube003.geometry}
        material={gltf.materials.outline}
        userData={{ name: 'Cube.003' }}
      />
      <T.Mesh
        name="BezierCircle"
        castShadow
        receiveShadow
        geometry={gltf.nodes.BezierCircle.geometry}
        material={gltf.materials.outline}
        userData={{ name: 'BezierCircle' }}
      />
      <T.Mesh
        name="BezierCircle001"
        castShadow
        receiveShadow
        geometry={gltf.nodes.BezierCircle001.geometry}
        material={gltf.materials.outline}
        userData={{ name: 'BezierCircle.001' }}
      />
      <T.Mesh
        name="BezierCircle002"
        castShadow
        receiveShadow
        geometry={gltf.nodes.BezierCircle002.geometry}
        material={gltf.materials.outline}
        userData={{ name: 'BezierCircle.002' }}
      />
      <T.Mesh
        name="BezierCircle003"
        castShadow
        receiveShadow
        geometry={gltf.nodes.BezierCircle003.geometry}
        material={gltf.materials.outline}
        userData={{ name: 'BezierCircle.003' }}
      />
      <T.Mesh
        name="BezierCircle004"
        castShadow
        receiveShadow
        geometry={gltf.nodes.BezierCircle004.geometry}
        material={gltf.materials.outline}
        userData={{ name: 'BezierCircle.004' }}
      />
      <T.Mesh
        name="BezierCircle005"
        castShadow
        receiveShadow
        geometry={gltf.nodes.BezierCircle005.geometry}
        material={gltf.materials.outline}
        userData={{ name: 'BezierCircle.005' }}
      />
      <T.Mesh
        name="BezierCircle006"
        castShadow
        receiveShadow
        geometry={gltf.nodes.BezierCircle006.geometry}
        material={gltf.materials.outline}
        userData={{ name: 'BezierCircle.006' }}
      />
      <T.Mesh
        name="BezierCircle007"
        castShadow
        receiveShadow
        geometry={gltf.nodes.BezierCircle007.geometry}
        material={gltf.materials.outline}
        userData={{ name: 'BezierCircle.007' }}
      />
      <T.Mesh
        name="WaveAnimated"
        castShadow
        receiveShadow
        geometry={gltf.nodes.WaveAnimated.geometry}
        material={gltf.materials.liquid}
        morphTargetDictionary={gltf.nodes.WaveAnimated.morphTargetDictionary}
        morphTargetInfluences={gltf.nodes.WaveAnimated.morphTargetInfluences}
        userData={{ targetNames: ['Wave'], name: 'WaveAnimated' }}
      />
      <T.Mesh
        name="Cube001"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Cube001.geometry}
        material={gltf.materials.top}
        morphTargetDictionary={gltf.nodes.Cube001.morphTargetDictionary}
        morphTargetInfluences={gltf.nodes.Cube001.morphTargetInfluences}
        userData={{ targetNames: ['Wave'], name: 'Cube.001' }}
      />
      <T.Mesh
        name="Outline"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Outline.geometry}
        material={gltf.materials.outline}
        morphTargetDictionary={gltf.nodes.Outline.morphTargetDictionary}
        morphTargetInfluences={gltf.nodes.Outline.morphTargetInfluences}
        userData={{ targetNames: ['Wave'], name: 'Outline' }}
      />
    </T.Group>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.()}
</T>
