name: Download Mautic and Deploy to Netcup

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      REMOTE_DIR: /httpdocs/mautic/ # Adjust this path to your Netcup folder

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Latest Mautic Production Build
        run: |
          LATEST_ZIP_URL=$(curl -s https://api.github.com/repos/mautic/mautic/releases/latest | grep "browser_download_url.*zip" | cut -d '"' -f 4 | head -n 1)
          curl -L $LATEST_ZIP_URL -o mautic.zip

      - name: Unzip Mautic
        run: |
          mkdir mautic_files
          unzip mautic.zip -d mautic_files
          rm mautic.zip

      - name: 🛠 Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: 🧹 Clear target directory on Netcup
        run: |
          sshpass -p "${{ secrets.SSH_PASS }}" ssh -o StrictHostKeyChecking=no ${{ env.SSH_USER }}@${{ env.SSH_HOST }} "rm -rf ${{ env.REMOTE_DIR }}*"

      - name: 📤 Deploy to Netcup via Rsync (Password Auth)
        run: |
          # The -e flag tells rsync to use sshpass for the ssh connection
          sshpass -p "${{ secrets.SSH_PASS }}" rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./mautic_files/ ${{ env.SSH_USER }}@${{ env.SSH_HOST }}:${{ env.REMOTE_DIR }}
